name: sensitive_example
description: Demonstrates the sensitive analyzer plugin.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.11.0

dependencies:
  sensitive:
    path: ../

dev_dependencies:
  arxdeus_lints: ^1.0.0
